import { BaseItem } from "@types";

/**
 * 縣市的選項
 */
export const CITY_OPTIONS: BaseItem[] = [
  { value: "臺北市", label: "臺北市" },
  { value: "新北市", label: "新北市" },
  { value: "基隆市", label: "基隆市" },
  { value: "桃園市", label: "桃園市" },
  { value: "新竹縣", label: "新竹縣" },
  { value: "新竹市", label: "新竹市" },
  { value: "苗栗縣", label: "苗栗縣" },
  { value: "臺中市", label: "臺中市" },
  { value: "南投縣", label: "南投縣" },
  { value: "彰化縣", label: "彰化縣" },
  { value: "雲林縣", label: "雲林縣" },
  { value: "嘉義縣", label: "嘉義縣" },
  { value: "嘉義市", label: "嘉義市" },
  { value: "臺南市", label: "臺南市" },
  { value: "高雄市", label: "高雄市" },
  { value: "屏東縣", label: "屏東縣" },
  { value: "宜蘭縣", label: "宜蘭縣" },
  { value: "花蓮縣", label: "花蓮縣" },
  { value: "臺東縣", label: "臺東縣" },
  { value: "澎湖縣", label: "澎湖縣" },
  { value: "金門縣", label: "金門縣" },
  { value: "連江縣", label: "連江縣" },
];

/**
 * 鄉鎮區的選項
 */
export const AREA_OPTIONS: Record<
  (typeof CITY_OPTIONS)[number]["value"],
  (BaseItem & { zipcode: string })[]
> = {
  臺北市: [
    { zipcode: "100", label: "中正區", value: "中正區" },
    { zipcode: "103", label: "大同區", value: "大同區" },
    { zipcode: "104", label: "中山區", value: "中山區" },
    { zipcode: "105", label: "松山區", value: "松山區" },
    { zipcode: "106", label: "大安區", value: "大安區" },
    { zipcode: "108", label: "萬華區", value: "萬華區" },
    { zipcode: "110", label: "信義區", value: "信義區" },
    { zipcode: "111", label: "士林區", value: "士林區" },
    { zipcode: "112", label: "北投區", value: "北投區" },
    { zipcode: "114", label: "內湖區", value: "內湖區" },
    { zipcode: "115", label: "南港區", value: "南港區" },
    { zipcode: "116", label: "文山區", value: "文山區" },
  ],
  新北市: [
    { zipcode: "207", label: "萬里區", value: "萬里區" },
    { zipcode: "208", label: "金山區", value: "金山區" },
    { zipcode: "220", label: "板橋區", value: "板橋區" },
    { zipcode: "221", label: "汐止區", value: "汐止區" },
    { zipcode: "222", label: "深坑區", value: "深坑區" },
    { zipcode: "223", label: "石碇區", value: "石碇區" },
    { zipcode: "224", label: "瑞芳區", value: "瑞芳區" },
    { zipcode: "226", label: "平溪區", value: "平溪區" },
    { zipcode: "227", label: "雙溪區", value: "雙溪區" },
    { zipcode: "228", label: "貢寮區", value: "貢寮區" },
    { zipcode: "231", label: "新店區", value: "新店區" },
    { zipcode: "232", label: "坪林區", value: "坪林區" },
    { zipcode: "233", label: "烏來區", value: "烏來區" },
    { zipcode: "234", label: "永和區", value: "永和區" },
    { zipcode: "235", label: "中和區", value: "中和區" },
    { zipcode: "236", label: "土城區", value: "土城區" },
    { zipcode: "237", label: "三峽區", value: "三峽區" },
    { zipcode: "238", label: "樹林區", value: "樹林區" },
    { zipcode: "239", label: "鶯歌區", value: "鶯歌區" },
    { zipcode: "241", label: "三重區", value: "三重區" },
    { zipcode: "242", label: "新莊區", value: "新莊區" },
    { zipcode: "243", label: "泰山區", value: "泰山區" },
    { zipcode: "244", label: "林口區", value: "林口區" },
    { zipcode: "247", label: "蘆洲區", value: "蘆洲區" },
    { zipcode: "248", label: "五股區", value: "五股區" },
    { zipcode: "249", label: "八里區", value: "八里區" },
    { zipcode: "251", label: "淡水區", value: "淡水區" },
    { zipcode: "252", label: "三芝區", value: "三芝區" },
    { zipcode: "253", label: "石門區", value: "石門區" },
  ],
  基隆市: [
    { zipcode: "200", label: "仁愛區", value: "仁愛區" },
    { zipcode: "201", label: "信義區", value: "信義區" },
    { zipcode: "202", label: "中正區", value: "中正區" },
    { zipcode: "203", label: "中山區", value: "中山區" },
    { zipcode: "204", label: "安樂區", value: "安樂區" },
    { zipcode: "205", label: "暖暖區", value: "暖暖區" },
    { zipcode: "206", label: "七堵區", value: "七堵區" },
  ],
  桃園市: [
    { value: "中壢區", label: "中壢區", zipcode: "320" },
    { value: "平鎮區", label: "平鎮區", zipcode: "324" },
    { value: "龍潭區", label: "龍潭區", zipcode: "325" },
    { value: "楊梅區", label: "楊梅區", zipcode: "326" },
    { value: "新屋區", label: "新屋區", zipcode: "327" },
    { value: "觀音區", label: "觀音區", zipcode: "328" },
    { value: "桃園區", label: "桃園區", zipcode: "330" },
    { value: "龜山區", label: "龜山區", zipcode: "333" },
    { value: "八德區", label: "八德區", zipcode: "334" },
    { value: "大溪區", label: "大溪區", zipcode: "335" },
    { value: "復興區", label: "復興區", zipcode: "336" },
    { value: "大園區", label: "大園區", zipcode: "337" },
    { value: "蘆竹區", label: "蘆竹區", zipcode: "338" },
  ],
  新竹市: [
    { value: "東區", label: "東區", zipcode: "300" },
    { value: "北區", label: "北區", zipcode: "300" },
    { value: "香山區", label: "香山區", zipcode: "300" },
  ],
  新竹縣: [
    { value: "竹北市", label: "竹北市", zipcode: "302" },
    { value: "湖口鄉", label: "湖口鄉", zipcode: "303" },
    { value: "新豐鄉", label: "新豐鄉", zipcode: "304" },
    { value: "新埔鎮", label: "新埔鎮", zipcode: "305" },
    { value: "關西鎮", label: "關西鎮", zipcode: "306" },
    { value: "芎林鄉", label: "芎林鄉", zipcode: "307" },
    { value: "寶山鄉", label: "寶山鄉", zipcode: "308" },
    { value: "竹東鎮", label: "竹東鎮", zipcode: "310" },
    { value: "五峰鄉", label: "五峰鄉", zipcode: "311" },
    { value: "橫山鄉", label: "橫山鄉", zipcode: "312" },
    { value: "尖石鄉", label: "尖石鄉", zipcode: "313" },
    { value: "北埔鄉", label: "北埔鄉", zipcode: "314" },
    { value: "峨眉鄉", label: "峨眉鄉", zipcode: "315" },
  ],
  苗栗縣: [
    { value: "竹南鎮", label: "竹南鎮", zipcode: "350" },
    { value: "頭份市", label: "頭份市", zipcode: "351" },
    { value: "三灣鄉", label: "三灣鄉", zipcode: "352" },
    { value: "南庄鄉", label: "南庄鄉", zipcode: "353" },
    { value: "獅潭鄉", label: "獅潭鄉", zipcode: "354" },
    { value: "後龍鎮", label: "後龍鎮", zipcode: "356" },
    { value: "通霄鎮", label: "通霄鎮", zipcode: "357" },
    { value: "苑裡鎮", label: "苑裡鎮", zipcode: "358" },
    { value: "苗栗市", label: "苗栗市", zipcode: "360" },
    { value: "造橋鄉", label: "造橋鄉", zipcode: "361" },
    { value: "頭屋鄉", label: "頭屋鄉", zipcode: "362" },
    { value: "公館鄉", label: "公館鄉", zipcode: "363" },
    { value: "大湖鄉", label: "大湖鄉", zipcode: "364" },
    { value: "泰安鄉", label: "泰安鄉", zipcode: "365" },
    { value: "銅鑼鄉", label: "銅鑼鄉", zipcode: "366" },
    { value: "三義鄉", label: "三義鄉", zipcode: "367" },
    { value: "西湖鄉", label: "西湖鄉", zipcode: "368" },
    { value: "卓蘭鎮", label: "卓蘭鎮", zipcode: "369" },
  ],
  臺中市: [
    { value: "中區", label: "中區", zipcode: "400" },
    { value: "東區", label: "東區", zipcode: "401" },
    { value: "南區", label: "南區", zipcode: "402" },
    { value: "西區", label: "西區", zipcode: "403" },
    { value: "北區", label: "北區", zipcode: "404" },
    { value: "北屯區", label: "北屯區", zipcode: "406" },
    { value: "西屯區", label: "西屯區", zipcode: "407" },
    { value: "南屯區", label: "南屯區", zipcode: "408" },
    { value: "太平區", label: "太平區", zipcode: "411" },
    { value: "大里區", label: "大里區", zipcode: "412" },
    { value: "霧峰區", label: "霧峰區", zipcode: "413" },
    { value: "烏日區", label: "烏日區", zipcode: "414" },
    { value: "豐原區", label: "豐原區", zipcode: "420" },
    { value: "后里區", label: "后里區", zipcode: "421" },
    { value: "石岡區", label: "石岡區", zipcode: "422" },
    { value: "東勢區", label: "東勢區", zipcode: "423" },
    { value: "和平區", label: "和平區", zipcode: "424" },
    { value: "新社區", label: "新社區", zipcode: "426" },
    { value: "潭子區", label: "潭子區", zipcode: "427" },
    { value: "大雅區", label: "大雅區", zipcode: "428" },
    { value: "神岡區", label: "神岡區", zipcode: "429" },
    { value: "大肚區", label: "大肚區", zipcode: "432" },
    { value: "沙鹿區", label: "沙鹿區", zipcode: "433" },
    { value: "龍井區", label: "龍井區", zipcode: "434" },
    { value: "梧棲區", label: "梧棲區", zipcode: "435" },
    { value: "清水區", label: "清水區", zipcode: "436" },
    { value: "大甲區", label: "大甲區", zipcode: "437" },
    { value: "外埔區", label: "外埔區", zipcode: "438" },
    { value: "大安區", label: "大安區", zipcode: "439" },
  ],
  彰化縣: [
    { value: "彰化市", label: "彰化市", zipcode: "500" },
    { value: "芬園鄉", label: "芬園鄉", zipcode: "502" },
    { value: "花壇鄉", label: "花壇鄉", zipcode: "503" },
    { value: "秀水鄉", label: "秀水鄉", zipcode: "504" },
    { value: "鹿港鎮", label: "鹿港鎮", zipcode: "505" },
    { value: "福興鄉", label: "福興鄉", zipcode: "506" },
    { value: "線西鄉", label: "線西鄉", zipcode: "507" },
    { value: "和美鎮", label: "和美鎮", zipcode: "508" },
    { value: "伸港鄉", label: "伸港鄉", zipcode: "509" },
    { value: "員林市", label: "員林市", zipcode: "510" },
    { value: "社頭鄉", label: "社頭鄉", zipcode: "511" },
    { value: "永靖鄉", label: "永靖鄉", zipcode: "512" },
    { value: "埔心鄉", label: "埔心鄉", zipcode: "513" },
    { value: "溪湖鎮", label: "溪湖鎮", zipcode: "514" },
    { value: "大村鄉", label: "大村鄉", zipcode: "515" },
    { value: "埔鹽鄉", label: "埔鹽鄉", zipcode: "516" },
    { value: "田中鎮", label: "田中鎮", zipcode: "520" },
    { value: "北斗鎮", label: "北斗鎮", zipcode: "521" },
    { value: "田尾鄉", label: "田尾鄉", zipcode: "522" },
    { value: "埤頭鄉", label: "埤頭鄉", zipcode: "523" },
    { value: "溪州鄉", label: "溪州鄉", zipcode: "524" },
    { value: "竹塘鄉", label: "竹塘鄉", zipcode: "525" },
    { value: "二林鎮", label: "二林鎮", zipcode: "526" },
    { value: "大城鄉", label: "大城鄉", zipcode: "527" },
    { value: "芳苑鄉", label: "芳苑鄉", zipcode: "528" },
    { value: "二水鄉", label: "二水鄉", zipcode: "530" },
  ],
  南投縣: [
    { value: "南投市", label: "南投市", zipcode: "540" },
    { value: "中寮鄉", label: "中寮鄉", zipcode: "541" },
    { value: "草屯鎮", label: "草屯鎮", zipcode: "542" },
    { value: "國姓鄉", label: "國姓鄉", zipcode: "544" },
    { value: "埔里鎮", label: "埔里鎮", zipcode: "545" },
    { value: "仁愛鄉", label: "仁愛鄉", zipcode: "546" },
    { value: "名間鄉", label: "名間鄉", zipcode: "551" },
    { value: "集集鎮", label: "集集鎮", zipcode: "552" },
    { value: "水里鄉", label: "水里鄉", zipcode: "553" },
    { value: "魚池鄉", label: "魚池鄉", zipcode: "555" },
    { value: "信義鄉", label: "信義鄉", zipcode: "556" },
    { value: "竹山鎮", label: "竹山鎮", zipcode: "557" },
    { value: "鹿谷鄉", label: "鹿谷鄉", zipcode: "558" },
  ],
  雲林縣: [
    { value: "斗南鎮", label: "斗南鎮", zipcode: "630" },
    { value: "大埤鄉", label: "大埤鄉", zipcode: "631" },
    { value: "虎尾鎮", label: "虎尾鎮", zipcode: "632" },
    { value: "土庫鎮", label: "土庫鎮", zipcode: "633" },
    { value: "褒忠鄉", label: "褒忠鄉", zipcode: "634" },
    { value: "東勢鄉", label: "東勢鄉", zipcode: "635" },
    { value: "臺西鄉", label: "臺西鄉", zipcode: "636" },
    { value: "崙背鄉", label: "崙背鄉", zipcode: "637" },
    { value: "麥寮鄉", label: "麥寮鄉", zipcode: "638" },
    { value: "斗六市", label: "斗六市", zipcode: "640" },
    { value: "林內鄉", label: "林內鄉", zipcode: "643" },
    { value: "古坑鄉", label: "古坑鄉", zipcode: "646" },
    { value: "莿桐鄉", label: "莿桐鄉", zipcode: "647" },
    { value: "西螺鎮", label: "西螺鎮", zipcode: "648" },
    { value: "二崙鄉", label: "二崙鄉", zipcode: "649" },
    { value: "北港鎮", label: "北港鎮", zipcode: "651" },
    { value: "水林鄉", label: "水林鄉", zipcode: "652" },
    { value: "口湖鄉", label: "口湖鄉", zipcode: "653" },
    { value: "四湖鄉", label: "四湖鄉", zipcode: "654" },
    { value: "元長鄉", label: "元長鄉", zipcode: "655" },
  ],
  嘉義市: [
    { value: "東區", label: "東區", zipcode: "600" },
    { value: "西區", label: "西區", zipcode: "600" },
  ],
  嘉義縣: [
    { value: "番路鄉", label: "番路鄉", zipcode: "602" },
    { value: "梅山鄉", label: "梅山鄉", zipcode: "603" },
    { value: "竹崎鄉", label: "竹崎鄉", zipcode: "604" },
    { value: "阿里山鄉", label: "阿里山鄉", zipcode: "605" },
    { value: "中埔鄉", label: "中埔鄉", zipcode: "606" },
    { value: "大埔鄉", label: "大埔鄉", zipcode: "607" },
    { value: "水上鄉", label: "水上鄉", zipcode: "608" },
    { value: "鹿草鄉", label: "鹿草鄉", zipcode: "611" },
    { value: "太保市", label: "太保市", zipcode: "612" },
    { value: "朴子市", label: "朴子市", zipcode: "613" },
    { value: "東石鄉", label: "東石鄉", zipcode: "614" },
    { value: "六腳鄉", label: "六腳鄉", zipcode: "615" },
    { value: "新港鄉", label: "新港鄉", zipcode: "616" },
    { value: "民雄鄉", label: "民雄鄉", zipcode: "621" },
    { value: "大林鎮", label: "大林鎮", zipcode: "622" },
    { value: "溪口鄉", label: "溪口鄉", zipcode: "623" },
    { value: "義竹鄉", label: "義竹鄉", zipcode: "624" },
    { value: "布袋鎮", label: "布袋鎮", zipcode: "625" },
  ],
  臺南市: [
    { value: "中西區", label: "中西區", zipcode: "700" },
    { value: "東區", label: "東區", zipcode: "701" },
    { value: "南區", label: "南區", zipcode: "702" },
    { value: "北區", label: "北區", zipcode: "704" },
    { value: "安平區", label: "安平區", zipcode: "708" },
    { value: "安南區", label: "安南區", zipcode: "709" },
    { value: "永康區", label: "永康區", zipcode: "710" },
    { value: "歸仁區", label: "歸仁區", zipcode: "711" },
    { value: "新化區", label: "新化區", zipcode: "712" },
    { value: "左鎮區", label: "左鎮區", zipcode: "713" },
    { value: "玉井區", label: "玉井區", zipcode: "714" },
    { value: "楠西區", label: "楠西區", zipcode: "715" },
    { value: "南化區", label: "南化區", zipcode: "716" },
    { value: "仁德區", label: "仁德區", zipcode: "717" },
    { value: "關廟區", label: "關廟區", zipcode: "718" },
    { value: "龍崎區", label: "龍崎區", zipcode: "719" },
    { value: "官田區", label: "官田區", zipcode: "720" },
    { value: "麻豆區", label: "麻豆區", zipcode: "721" },
    { value: "佳里區", label: "佳里區", zipcode: "722" },
    { value: "西港區", label: "西港區", zipcode: "723" },
    { value: "七股區", label: "七股區", zipcode: "724" },
    { value: "將軍區", label: "將軍區", zipcode: "725" },
    { value: "學甲區", label: "學甲區", zipcode: "726" },
    { value: "北門區", label: "北門區", zipcode: "727" },
    { value: "新營區", label: "新營區", zipcode: "730" },
    { value: "後壁區", label: "後壁區", zipcode: "731" },
    { value: "白河區", label: "白河區", zipcode: "732" },
    { value: "東山區", label: "東山區", zipcode: "733" },
    { value: "六甲區", label: "六甲區", zipcode: "734" },
    { value: "下營區", label: "下營區", zipcode: "735" },
    { value: "柳營區", label: "柳營區", zipcode: "736" },
    { value: "鹽水區", label: "鹽水區", zipcode: "737" },
    { value: "善化區", label: "善化區", zipcode: "741" },
    { value: "大內區", label: "大內區", zipcode: "742" },
    { value: "山上區", label: "山上區", zipcode: "743" },
    { value: "新市區", label: "新市區", zipcode: "744" },
    { value: "安定區", label: "安定區", zipcode: "745" },
  ],
  高雄市: [
    { value: "新興區", label: "新興區", zipcode: "800" },
    { value: "前金區", label: "前金區", zipcode: "801" },
    { value: "苓雅區", label: "苓雅區", zipcode: "802" },
    { value: "鹽埕區", label: "鹽埕區", zipcode: "803" },
    { value: "鼓山區", label: "鼓山區", zipcode: "804" },
    { value: "旗津區", label: "旗津區", zipcode: "805" },
    { value: "前鎮區", label: "前鎮區", zipcode: "806" },
    { value: "三民區", label: "三民區", zipcode: "807" },
    { value: "楠梓區", label: "楠梓區", zipcode: "811" },
    { value: "小港區", label: "小港區", zipcode: "812" },
    { value: "左營區", label: "左營區", zipcode: "813" },
    { value: "仁武區", label: "仁武區", zipcode: "814" },
    { value: "大社區", label: "大社區", zipcode: "815" },
    { value: "東沙群島", label: "東沙群島", zipcode: "817" },
    { value: "南沙群島", label: "南沙群島", zipcode: "819" },
    { value: "岡山區", label: "岡山區", zipcode: "820" },
    { value: "路竹區", label: "路竹區", zipcode: "821" },
    { value: "阿蓮區", label: "阿蓮區", zipcode: "822" },
    { value: "田寮區", label: "田寮區", zipcode: "823" },
    { value: "燕巢區", label: "燕巢區", zipcode: "824" },
    { value: "橋頭區", label: "橋頭區", zipcode: "825" },
    { value: "梓官區", label: "梓官區", zipcode: "826" },
    { value: "彌陀區", label: "彌陀區", zipcode: "827" },
    { value: "永安區", label: "永安區", zipcode: "828" },
    { value: "湖內區", label: "湖內區", zipcode: "829" },
    { value: "鳳山區", label: "鳳山區", zipcode: "830" },
    { value: "大寮區", label: "大寮區", zipcode: "831" },
    { value: "林園區", label: "林園區", zipcode: "832" },
    { value: "鳥松區", label: "鳥松區", zipcode: "833" },
    { value: "大樹區", label: "大樹區", zipcode: "840" },
    { value: "旗山區", label: "旗山區", zipcode: "842" },
    { value: "美濃區", label: "美濃區", zipcode: "843" },
    { value: "六龜區", label: "六龜區", zipcode: "844" },
    { value: "內門區", label: "內門區", zipcode: "845" },
    { value: "杉林區", label: "杉林區", zipcode: "846" },
    { value: "甲仙區", label: "甲仙區", zipcode: "847" },
    { value: "桃源區", label: "桃源區", zipcode: "848" },
    { value: "那瑪夏區", label: "那瑪夏區", zipcode: "849" },
    { value: "茂林區", label: "茂林區", zipcode: "851" },
    { value: "茄萣區", label: "茄萣區", zipcode: "852" },
  ],
  屏東縣: [
    { value: "屏東市", label: "屏東市", zipcode: "900" },
    { value: "三地門鄉", label: "三地門鄉", zipcode: "901" },
    { value: "霧臺鄉", label: "霧臺鄉", zipcode: "902" },
    { value: "瑪家鄉", label: "瑪家鄉", zipcode: "903" },
    { value: "九如鄉", label: "九如鄉", zipcode: "904" },
    { value: "里港鄉", label: "里港鄉", zipcode: "905" },
    { value: "高樹鄉", label: "高樹鄉", zipcode: "906" },
    { value: "鹽埔鄉", label: "鹽埔鄉", zipcode: "907" },
    { value: "長治鄉", label: "長治鄉", zipcode: "908" },
    { value: "麟洛鄉", label: "麟洛鄉", zipcode: "909" },
    { value: "竹田鄉", label: "竹田鄉", zipcode: "911" },
    { value: "內埔鄉", label: "內埔鄉", zipcode: "912" },
    { value: "萬丹鄉", label: "萬丹鄉", zipcode: "913" },
    { value: "潮州鎮", label: "潮州鎮", zipcode: "920" },
    { value: "泰武鄉", label: "泰武鄉", zipcode: "921" },
    { value: "來義鄉", label: "來義鄉", zipcode: "922" },
    { value: "萬巒鄉", label: "萬巒鄉", zipcode: "923" },
    { value: "崁頂鄉", label: "崁頂鄉", zipcode: "924" },
    { value: "新埤鄉", label: "新埤鄉", zipcode: "925" },
    { value: "南州鄉", label: "南州鄉", zipcode: "926" },
    { value: "林邊鄉", label: "林邊鄉", zipcode: "927" },
    { value: "東港鎮", label: "東港鎮", zipcode: "928" },
    { value: "琉球鄉", label: "琉球鄉", zipcode: "929" },
    { value: "佳冬鄉", label: "佳冬鄉", zipcode: "931" },
    { value: "新園鄉", label: "新園鄉", zipcode: "932" },
    { value: "枋寮鄉", label: "枋寮鄉", zipcode: "940" },
    { value: "枋山鄉", label: "枋山鄉", zipcode: "941" },
    { value: "春日鄉", label: "春日鄉", zipcode: "942" },
    { value: "獅子鄉", label: "獅子鄉", zipcode: "943" },
    { value: "車城鄉", label: "車城鄉", zipcode: "944" },
    { value: "牡丹鄉", label: "牡丹鄉", zipcode: "945" },
    { value: "恆春鎮", label: "恆春鎮", zipcode: "946" },
    { value: "滿州鄉", label: "滿州鄉", zipcode: "947" },
  ],
  宜蘭線: [
    { value: "宜蘭市", label: "宜蘭市", zipcode: "260" },
    { value: "頭城鎮", label: "頭城鎮", zipcode: "261" },
    { value: "礁溪鄉", label: "礁溪鄉", zipcode: "262" },
    { value: "壯圍鄉", label: "壯圍鄉", zipcode: "263" },
    { value: "員山鄉", label: "員山鄉", zipcode: "264" },
    { value: "羅東鎮", label: "羅東鎮", zipcode: "265" },
    { value: "三星鄉", label: "三星鄉", zipcode: "266" },
    { value: "大同鄉", label: "大同鄉", zipcode: "267" },
    { value: "五結鄉", label: "五結鄉", zipcode: "268" },
    { value: "冬山鄉", label: "冬山鄉", zipcode: "269" },
    { value: "蘇澳鎮", label: "蘇澳鎮", zipcode: "270" },
    { value: "南澳鄉", label: "南澳鄉", zipcode: "272" },
    // { value: '釣魚台', label: '釣魚台', zipcode: '290' }
  ],
  花蓮縣: [
    { value: "花蓮市", label: "花蓮市", zipcode: "970" },
    { value: "新城鄉", label: "新城鄉", zipcode: "971" },
    { value: "秀林鄉", label: "秀林鄉", zipcode: "972" },
    { value: "吉安鄉", label: "吉安鄉", zipcode: "973" },
    { value: "壽豐鄉", label: "壽豐鄉", zipcode: "974" },
    { value: "鳳林鎮", label: "鳳林鎮", zipcode: "975" },
    { value: "光復鄉", label: "光復鄉", zipcode: "976" },
    { value: "豐濱鄉", label: "豐濱鄉", zipcode: "977" },
    { value: "瑞穗鄉", label: "瑞穗鄉", zipcode: "978" },
    { value: "萬榮鄉", label: "萬榮鄉", zipcode: "979" },
    { value: "玉里鎮", label: "玉里鎮", zipcode: "981" },
    { value: "卓溪鄉", label: "卓溪鄉", zipcode: "982" },
    { value: "富里鄉", label: "富里鄉", zipcode: "983" },
  ],
  臺東縣: [
    { value: "臺東市", label: "臺東市", zipcode: "950" },
    { value: "綠島鄉", label: "綠島鄉", zipcode: "951" },
    { value: "蘭嶼鄉", label: "蘭嶼鄉", zipcode: "952" },
    { value: "延平鄉", label: "延平鄉", zipcode: "953" },
    { value: "卑南鄉", label: "卑南鄉", zipcode: "954" },
    { value: "鹿野鄉", label: "鹿野鄉", zipcode: "955" },
    { value: "關山鎮", label: "關山鎮", zipcode: "956" },
    { value: "海端鄉", label: "海端鄉", zipcode: "957" },
    { value: "池上鄉", label: "池上鄉", zipcode: "958" },
    { value: "東河鄉", label: "東河鄉", zipcode: "959" },
    { value: "成功鎮", label: "成功鎮", zipcode: "961" },
    { value: "長濱鄉", label: "長濱鄉", zipcode: "962" },
    { value: "太麻里鄉", label: "太麻里鄉", zipcode: "963" },
    { value: "金峰鄉", label: "金峰鄉", zipcode: "964" },
    { value: "大武鄉", label: "大武鄉", zipcode: "965" },
    { value: "達仁鄉", label: "達仁鄉", zipcode: "966" },
  ],
  澎湖縣: [
    { value: "馬公市", label: "馬公市", zipcode: "880" },
    { value: "西嶼鄉", label: "西嶼鄉", zipcode: "881" },
    { value: "望安鄉", label: "望安鄉", zipcode: "882" },
    { value: "七美鄉", label: "七美鄉", zipcode: "883" },
    { value: "白沙鄉", label: "白沙鄉", zipcode: "884" },
    { value: "湖西鄉", label: "湖西鄉", zipcode: "885" },
  ],
  金門縣: [
    { value: "金湖鎮", label: "金湖鎮", zipcode: "891" },
    { value: "金沙鎮", label: "金沙鎮", zipcode: "890" },
    { value: "金寧鄉", label: "金寧鄉", zipcode: "892" },
    { value: "金城鎮", label: "金城鎮", zipcode: "893" },
    { value: "烈嶼鄉", label: "烈嶼鄉", zipcode: "894" },
    { value: "烏坵鄉", label: "烏坵鄉", zipcode: "896" },
  ],
  連江縣: [
    { value: "南竿鄉", label: "南竿鄉", zipcode: "209" },
    { value: "北竿鄉", label: "北竿鄉", zipcode: "210" },
    { value: "莒光鄉", label: "莒光鄉", zipcode: "211" },
    { value: "東引鄉", label: "東引鄉", zipcode: "212" },
  ],
};
